{"level":"error","message":"Uncaught Exceptions  THROW NEW ERROR","stack":"Error: THROW NEW ERROR\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:118:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)\n    at phase4 (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\bin.ts:649:14)\n    at bootstrap (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\bin.ts:95:10)"}
{"level":"error","message":"Uncaught Exceptions  express.router is not a function","stack":"TypeError: express.router is not a function\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:2:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:77:18)"}
{"level":"error","message":"Uncaught Exceptions  Cannot read properties of undefined (reading 'length')","stack":"TypeError: Cannot read properties of undefined (reading 'length')\n    at pathtoRegexp (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\path-to-regexp\\index.js:63:49)\n    at new Layer (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\layer.js:45:17)\n    at Function.route (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\index.js:505:15)\n    at Function.proto.<computed> [as post] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\index.js:520:22)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:78:30)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)"}
{"level":"error","message":"Uncaught Exceptions  app.use() requires a middleware function","stack":"TypeError: app.use() requires a middleware function\n    at Function.use (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:217:11)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:78:5)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)\n    at phase4 (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\bin.ts:649:14)"}
{"level":"error","message":"Uncaught Exceptions  Cannot read properties of undefined (reading 'method')","stack":"TypeError: Cannot read properties of undefined (reading 'method')\n    at Function.handle (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\index.js:139:34)\n    at router (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:78:21)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)"}
{"code":"MODULE_NOT_FOUND","level":"error","message":"Uncaught Exceptions  Cannot find module './routes/tryRouter'\nRequire stack:\n- C:\\Work Espace (dhia)\\chwanet\\server\\server.ts","requireStack":["C:\\Work Espace (dhia)\\chwanet\\server\\server.ts"],"stack":"Error: Cannot find module './routes/tryRouter'\nRequire stack:\n- C:\\Work Espace (dhia)\\chwanet\\server\\server.ts\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\@cspotcode\\source-map-support\\source-map-support.js:811:30)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:77:19)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)"}
{"code":"MODULE_NOT_FOUND","level":"error","message":"Uncaught Exceptions  Cannot find module './routes/tryRouter'\nRequire stack:\n- C:\\Work Espace (dhia)\\chwanet\\server\\server.ts","requireStack":["C:\\Work Espace (dhia)\\chwanet\\server\\server.ts"],"stack":"Error: Cannot find module './routes/tryRouter'\nRequire stack:\n- C:\\Work Espace (dhia)\\chwanet\\server\\server.ts\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\@cspotcode\\source-map-support\\source-map-support.js:811:30)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:77:19)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)"}
{"level":"error","message":"Uncaught Exceptions  auth is not defined","stack":"ReferenceError: auth is not defined\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\me.ts:7:17)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:57:12)"}
{"level":"error","message":"Uncaught Exceptions  Router.use() requires a middleware function but got a Object","stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:43:5)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)"}
{"level":"error","message":"Uncaught Exceptions  Router.use() requires a middleware function but got a Object","stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:43:5)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)"}
{"level":"error","message":"Uncaught Exceptions  Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.","stack":"TypeError: Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:699:13)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:750:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Schema.interpretAsType (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1379:29)\n    at Schema.path (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1065:27)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:719:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\models\\Profiles.ts:38:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)"}
{"level":"error","message":"Uncaught Exceptions  Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.","stack":"TypeError: Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:699:13)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:750:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Schema.interpretAsType (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1379:29)\n    at Schema.path (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1065:27)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:719:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\models\\Profiles.ts:38:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)"}
{"level":"error","message":"Uncaught Exceptions  Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.","stack":"TypeError: Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:699:13)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:750:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Schema.interpretAsType (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1379:29)\n    at Schema.path (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1065:27)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:719:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\models\\Profiles.ts:34:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)"}
{"level":"error","message":"Uncaught Exceptions  Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.","stack":"TypeError: Invalid schema configuration: `true` is not a valid type at path `require`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:699:13)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Schema.interpretAsType (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1379:29)\n    at Schema.path (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1065:27)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:719:12)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)\n    at Schema.interpretAsType (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1379:29)\n    at Schema.path (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:1065:27)\n    at Schema.add (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:784:14)\n    at new Schema (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema.js:137:10)"}
{"level":"error","message":"Uncaught Exceptions  2nd argument to `Model` must be a POJO or string, **not** a schema. Make sure you're calling `mongoose.model()`, not `mongoose.Model()`.","stack":"TypeError: 2nd argument to `Model` must be a POJO or string, **not** a schema. Make sure you're calling `mongoose.model()`, not `mongoose.Model()`.\n    at new Model (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\model.js:119:11)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\models\\Profiles.ts:67:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)"}
{"level":"error","message":"Uncaught Exceptions  2nd argument to `Model` must be a POJO or string, **not** a schema. Make sure you're calling `mongoose.model()`, not `mongoose.Model()`.","stack":"TypeError: 2nd argument to `Model` must be a POJO or string, **not** a schema. Make sure you're calling `mongoose.model()`, not `mongoose.Model()`.\n    at new Model (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\model.js:119:11)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\models\\Profiles.ts:67:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)"}
{"level":"error","message":"Uncaught Exceptions  2nd argument to `Model` must be a POJO or string, **not** a schema. Make sure you're calling `mongoose.model()`, not `mongoose.Model()`.","stack":"TypeError: 2nd argument to `Model` must be a POJO or string, **not** a schema. Make sure you're calling `mongoose.model()`, not `mongoose.Model()`.\n    at new Model (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\model.js:119:11)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\models\\Profiles.ts:67:24)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)"}
{"diagnosticCodes":[7009],"level":"error","message":"Uncaught Exceptions  ⨯ Unable to compile TypeScript:\n\u001b[96mmodels/Profiles.ts\u001b[0m:\u001b[93m67\u001b[0m:\u001b[93m24\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS7009: \u001b[0m'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.\r\n\r\n\u001b[7m67\u001b[0m const ProfilesModels = new mongoose.model('Profiles',ProfilesSchema)\r\n\u001b[7m  \u001b[0m \u001b[91m                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u001b[0m\r\n","stack":"TSError: ⨯ Unable to compile TypeScript:\n\u001b[96mmodels/Profiles.ts\u001b[0m:\u001b[93m67\u001b[0m:\u001b[93m24\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS7009: \u001b[0m'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.\r\n\r\n\u001b[7m67\u001b[0m const ProfilesModels = new mongoose.model('Profiles',ProfilesSchema)\r\n\u001b[7m  \u001b[0m \u001b[91m                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u001b[0m\r\n\n    at createTSError (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:859:12)\n    at reportTSError (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:863:19)\n    at getOutput (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1077:36)\n    at Object.compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1433:41)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1617:30)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data and salt arguments required","stack":"Error: data and salt arguments required\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:137:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data and salt arguments required","stack":"Error: data and salt arguments required\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:137:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data and salt arguments required","stack":"Error: data and salt arguments required\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:137:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data and salt arguments required","stack":"Error: data and salt arguments required\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:137:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data and salt arguments required","stack":"Error: data and salt arguments required\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:137:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data and salt arguments required","stack":"Error: data and salt arguments required\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:137:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data must be a string or Buffer and salt must either be a salt string or a number of rounds","stack":"Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:144:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data must be a string or Buffer and salt must either be a salt string or a number of rounds","stack":"Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:144:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data must be a string or Buffer and salt must either be a salt string or a number of rounds","stack":"Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:144:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error data must be a string or Buffer and salt must either be a salt string or a number of rounds","stack":"Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:144:17)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.hash (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\bcrypt\\bcrypt.js:133:25)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:15:41\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\register.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"kind":"Number","level":"error","message":"there is an error Cast to Number failed for value \"5055555554huion\" (type string) at path \"phone\" for model \"Users\"","path":"phone","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stack":"CastError: Cast to Number failed for value \"5055555554huion\" (type string) at path \"phone\" for model \"Users\"\n    at SchemaNumber.cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema\\number.js:380:11)\n    at SchemaNumber.SchemaType.applySetters (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schematype.js:1220:12)\n    at SchemaNumber.castForQuery (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema\\number.js:432:14)\n    at cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\cast.js:356:32)\n    at model.Query.Query.cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4900:12)\n    at model.Query.Query._castConditions (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:2223:10)\n    at model.Query._findOne (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:2510:8)\n    at model.Query.exec (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4419:28)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","stringValue":"\"5055555554huion\"","value":"5055555554huion","valueType":"string"}
{"kind":"Number","level":"error","message":"there is an error Cast to Number failed for value \"123456789hh\" (type string) at path \"phone\" for model \"Users\"","path":"phone","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stack":"CastError: Cast to Number failed for value \"123456789hh\" (type string) at path \"phone\" for model \"Users\"\n    at SchemaNumber.cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema\\number.js:380:11)\n    at SchemaNumber.SchemaType.applySetters (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schematype.js:1220:12)\n    at SchemaNumber.castForQuery (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema\\number.js:432:14)\n    at cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\cast.js:356:32)\n    at model.Query.Query.cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4900:12)\n    at model.Query.Query._castConditions (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:2223:10)\n    at model.Query._findOne (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:2510:8)\n    at model.Query.exec (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4419:28)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","stringValue":"\"123456789hh\"","value":"123456789hh","valueType":"string"}
{"kind":"Number","level":"error","message":"there is an error Cast to Number failed for value \"12345678hj\" (type string) at path \"phone\" for model \"Users\"","path":"phone","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stack":"CastError: Cast to Number failed for value \"12345678hj\" (type string) at path \"phone\" for model \"Users\"\n    at SchemaNumber.cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema\\number.js:380:11)\n    at SchemaNumber.SchemaType.applySetters (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schematype.js:1220:12)\n    at SchemaNumber.castForQuery (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\schema\\number.js:432:14)\n    at cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\cast.js:356:32)\n    at model.Query.Query.cast (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4900:12)\n    at model.Query.Query._castConditions (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:2223:10)\n    at model.Query._findOne (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:2510:8)\n    at model.Query.exec (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4419:28)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","stringValue":"\"12345678hj\"","value":"12345678hj","valueType":"string"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exceptions  listen EADDRINUSE: address already in use :::8000","port":8000,"stack":"Error: listen EADDRINUSE: address already in use :::8000\n    at Server.setupListenHandle [as _listen2] (node:net:1469:16)\n    at listenInCluster (node:net:1517:12)\n    at Server.listen (node:net:1605:7)\n    at Function.listen (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:68:5)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)","syscall":"listen"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exceptions  listen EADDRINUSE: address already in use :::8000","port":8000,"stack":"Error: listen EADDRINUSE: address already in use :::8000\n    at Server.setupListenHandle [as _listen2] (node:net:1469:16)\n    at listenInCluster (node:net:1517:12)\n    at Server.listen (node:net:1605:7)\n    at Function.listen (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:68:5)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)","syscall":"listen"}
{"code":11000,"index":0,"keyPattern":{"phone":1},"keyValue":{"phone":16165464646},"level":"error","message":"there is an error E11000 duplicate key error collection: chwanett.users index: phone_1 dup key: { phone: 16165464646.0 }","stack":"MongoServerError: E11000 duplicate key error collection: chwanett.users index: phone_1 dup key: { phone: 16165464646.0 }\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\operations\\insert.ts:85:25\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\cmap\\connection_pool.ts:574:11\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\sdam\\server.ts:384:13\n    at handleOperationResult (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\sdam\\server.ts:532:14)\n    at Connection.onMessage (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\cmap\\connection.ts:418:5)\n    at MessageStream.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\cmap\\connection.ts:243:56)\n    at MessageStream.emit (node:events:513:28)\n    at MessageStream.emit (node:domain:489:12)\n    at processIncomingData (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\cmap\\message_stream.ts:193:12)\n    at MessageStream._write (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongodb\\src\\cmap\\message_stream.ts:74:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"there is an error Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:393:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:23:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Work Espace (dhia)\\chwanet\\server\\routes\\login.ts:5:58)"}
{"code":"MODULE_NOT_FOUND","level":"error","message":"Uncaught Exceptions  Cannot find module './routes/me'\nRequire stack:\n- C:\\Work Espace (dhia)\\chwanet\\server\\server.ts","requireStack":["C:\\Work Espace (dhia)\\chwanet\\server\\server.ts"],"stack":"Error: Cannot find module './routes/me'\nRequire stack:\n- C:\\Work Espace (dhia)\\chwanet\\server\\server.ts\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\@cspotcode\\source-map-support\\source-map-support.js:811:30)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\server.ts:47:12)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module.m._compile (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Object.require.extensions.<computed> [as .ts] (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\ts-node\\src\\index.ts:1621:12)"}
{"level":"error","message":"there is an error Operation `users.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"can't connect with dataBase Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"atlas-2jap10-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:788:11)\n    at NativeConnection.openUri (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\connection.js:763:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"there is an error Operation `workers.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `workers.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `workers.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `workers.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"level":"error","message":"there is an error Operation `workers.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `workers.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:185:23)\n    at listOnTimeout (node:internal/timers:564:17)\n    at processTimers (node:internal/timers:507:7)"}
{"body":"{\r\n    \"photo\":\"baha.img\",\r\n    \"discreption\":\"sportif\",\r\n    \"workName\":\"sport\",\r\n    \"team\":true,\r\n    \"experience\":5,\r\n\r\n}","expose":true,"level":"error","message":"there is an error Expected double-quoted property name in JSON at position 124","stack":"SyntaxError: Expected double-quoted property name in JSON at position 124\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at invokeCallback (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:513:28)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)","status":400,"statusCode":400,"type":"entity.parse.failed"}
{"body":"{\r\n    \"photo\":\"baha.img\",\r\n    \"discreption\":\"sportif\",\r\n    \"workName\":\"sport\",\r\n    \"team\":true,\r\n    \"experience\":5,\r\n\r\n}","expose":true,"level":"error","message":"there is an error Expected double-quoted property name in JSON at position 124","stack":"SyntaxError: Expected double-quoted property name in JSON at position 124\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at invokeCallback (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:513:28)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)","status":400,"statusCode":400,"type":"entity.parse.failed"}
{"body":"{\r\n    \"photo\":\"baha.img\",\r\n    \"discreption\":\"sportif\",\r\n    \"workName\":\"sport\",\r\n    \"team\":true,\r\n    \"experience\":5,\r\n\r\n}","expose":true,"level":"error","message":"there is an error Expected double-quoted property name in JSON at position 124","stack":"SyntaxError: Expected double-quoted property name in JSON at position 124\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at invokeCallback (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:513:28)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)","status":400,"statusCode":400,"type":"entity.parse.failed"}
{"level":"error","message":"there is an error Invalid update pipeline operator: \"workName\"","stack":"MongooseError: Invalid update pipeline operator: \"workName\"\n    at castPipelineOperator (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:146:9)\n    at castUpdate (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:40:22)\n    at model.Query._castUpdate (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4699:10)\n    at model.Query._findOneAndUpdate (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:3313:23)\n    at model.Query.exec (C:\\Work Espace (dhia)\\chwanet\\server\\node_modules\\mongoose\\lib\\query.js:4419:28)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
